name: build

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          # use Java 8
          java-version: adopt@1.8
      - name: Compile
        run: sbt compile
