name: release

on:
  push:
    tags:
      - '*'

env:
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}

jobs:
  releasse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          # use Java 8
          java-version: adopt@1.8
      - name: Release to bintray
        run: |
          sbt publish
          sbt bintrayRelease
